cloudProvider:
  azure:
    subscription: string
    application_id: string
    application_secret: string
    tenant: string
QVpVUkVfS0VZVkFVTFQ9c3luZXJhLWQtYWt2LTAwMDAxCkFaVVJFX0NMSUVOVF9JRD0xNjhmM2JlMS1jNTFlLTQ0NjAtOTRmZi1jNzI5ZDNlYWQyZmIKQVpVUkVfQ0xJRU5UX1NFQ1JFVD13eTc4UX5oNUxfbzAyRE5HT3JGdER6aGdlTHp0NWxsUzFDVmpyYU80CkFaVVJFX1NVQlNDUklQVElPTl9JRD1lYTlmMjczNy0zMDA2LTRkMmYtYjM3NS0xNzdjNzA4NjY3NDMKQVpVUkVfVEVOQU5UX0lEPTk1YjRjNWUzLTA0M2QtNDcyMS1hZjlmLWRlNTAzOWZmNzA1MQo=
